import {
  Check,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  Dices,
  Home,
  HelpCircle,
  Loader2,
  LogOut,
  Trash,
  Settings,
  Search,
  Slash,
  MoreVertical,
  Plus,
  AlertTriangle,
  User,
  ArrowRight,
  ArrowLeft,
  Sun,
  X,
  XCircle,
  type Icon as LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  logo: Dices,
  close: X,
  closeCircle: XCircle,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  help: HelpCircle,
  home: Home,
  check: Check,
  checkCircle: CheckCircle,
  logout: LogOut,
  search: Search,
  slash: Slash,
  sun: Sun,
};
